### PR TITLE
Update third parties to latest

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by christianparpart** [comment]
Oh. Wow! Many thanks @data-man. I know it's just a little PR, but I really appreciate that. Many thanks!

NB: You're adding/removing some includes. How did you decided  to do that? What Compiler did you maybe use that has been hinting that?

**Comment by christianparpart** [comment]
@data-man I was just merging a *huge* branch into master. So this is why I was updating your branch to be rebased on top of latest master, FYI. When tests get green (the important ones), I'll merge. :)

**Comment by data-man** [comment]
> How did you decided to do that?

```In file included from /home/dataman/Projects/C/-Terminals/contour_test/src/crispy/App.cpp:15:
/home/dataman/Projects/C/-Terminals/contour_test/src/crispy/debuglog.h: In function ‘crispy::debugtag::tag_id crispy::debugtag::make(std::string_view, std::string_view, bool)’:
/home/dataman/Projects/C/-Terminals/contour_test/src/crispy/debuglog.h:105:9: error: ‘assert’ was not declared in this scope
  105 |         assert(crispy::none_of(store(), [&](tag_info const& x) { return x.name == _name; }));
      |         ^~~~~~
/home/dataman/Projects/C/-Terminals/contour_test/src/crispy/debuglog.h:39:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
   38 |         #include <experimental/source_location>
  +++ |+#include <cassert>
   39 |         #define CRISPY_SOURCE_LOCATION 1
make[2]: *** [src/crispy/CMakeFiles/crispy-core.dir/build.make:76: src/crispy/CMakeFiles/crispy-core.dir/App.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:588: src/crispy/CMakeFiles/crispy-core.dir/all] Error 2
```
The same reason for other files (gcc 11.1.0).

**Comment by data-man** [comment]
Reased and force-pushed, but
> First-time contributors need a maintainer to approve running workflows

:smile:

**Comment by christianparpart** [comment]
Many thanks, @data-man :)

**Pull request merged**
