### PR TITLE
Update libunicode to latest

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by christianparpart** [comment]
That's interesting. the windows build fails because there is no `catch2/catch_all.hpp` (which is only available in the latest Catch2 beta), but it does build on the other platforms? Hmm...

**Comment by christianparpart** [comment]
> Maybe use devel Catch2 in Contour too?

I think it makes sense to ease the use of Catch2 in the sub repos and the parent repo. yeah.

**Comment by data-man** [comment]
Merged to #270. :(

**Comment by christianparpart** [comment]
> Merged to #270. :(

Oops. Did i do a mistake here? If so, i must apologize for that

**Comment by data-man** [comment]
> Did i do a mistake here?

Why? No!

**Pull request closed without merging**
