### PR TITLE
ci: use archlinux/archlinux image which is the official archlinux image

### PR DESCRIPTION
**Pull request by ResuBaka**
Instead of an image that is build from an 3party that builds an arch linux based image, we should use the offical image, in my opinion.

### CODE REVIEW

**Comment by uspasojevic96** [comment]
Steps need to be updated in the yml file due to not using buildx anymore

**Comment by ResuBaka** [comment]
We still use buildx and why should there be an update to the action task as it still uses this dockerfile as the entry. Can you explain it @uspasojevic96 ?

**Comment by uspasojevic96** [comment]
My bad, I was thinking that GHA supports Docker natively

**Comment by christianparpart** [comment]
FYI: I have been updating the base branch just now. Many thanks for your contribution @ResuBaka - I will see if that becomes green soon.

**Comment by christianparpart** [comment]
It's green! Happy Eastr! :egg: :hatching_chick:

**Pull request merged**
