### PR TITLE
Update yaml-cpp to latest

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by christianparpart** [comment]
💟 many thanks :)

**Comment by data-man** [comment]
What if to use https://github.com/cpm-cmake/CPM.cmake (requires CMake >= 3.14)?

**Comment by christianparpart** [comment]
> 

> What if to use https://github.com/cpm-cmake/CPM.cmake (requires CMake >= 3.14)?

I think fetchcontent is fine for now, isn't it? P.s. didn't check cpm in detail yet.

**Comment by data-man** [comment]
Yes, fetchcontent is fine, but cpm is finest. :)

**Pull request merged**
