### PR TITLE
notcurses-demo exposed bugfixes

### LINKED ISSUE #217: "Calculated current line does not match" followed by assert()
## Description

*NOTE: i just realized i was using TERM=vte-256color throughout. I'm going to switch to TERM=contour/TERM=contour-latest and try again. Nonetheless, I wouldn't expect segfaults from improper escape codes, if that's what was happening.*

Running `contour` from tip of master 2021-04-19 5daf772d99cb17319ee6426df03c6a013d4e27a8 on Compiz 0.8 on Linux 5.11.15, Debian Unstable. I'm the author of [Notcurses](https://github.com/dankamongmen/notcurses), a "blingful TUI library". I was trying out contour by running `notcurses-demo` from my 2.2.8 release (same behavior with tip of master). During the first demo, `intro`, I get the following output:

```
==================================================================================================================================
Calculated current line does not match.
==================================================================================================================================
Rendered screen at the time of failure: 130x64
cursor position      : (64:1, (invis))
vertical margins     : 1..64
horizontal margins   : 1..130
==================================================================================================================================
```

followed by

```c
contour: ../src/terminal/Screen.cpp:517: void terminal::Screen::fail(const string&) const: Assertion `false' failed.
```

The same thing happened with most of my other example programs. `pixel ../data/warmech.bmp` elicited:

```
==================================================================================================================================
Calculated current line does not match.
==================================================================================================================================
Rendered screen at the time of failure: 130x30
cursor position      : (10:1, (invis))
vertical margins     : 1..30
horizontal margins   : 1..130
==================================================================================================================================
```

followed by the same assertion failure. Both of these programs were driving Sixels. I then ran a non-Sixel program, and got a straight segfault (`zalgo`, exercising some complex Unicode):

```c
[schwarzgerat](0) $ valgrind --tool=memcheck src/contour/contour
==511403== Memcheck, a memory error detector
==511403== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==511403== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==511403== Command: src/contour/contour
==511403== 
==511403== Warning: noted but unhandled ioctl 0x5441 with no size/direction hints.
==511403==    This could cause spurious value errors to appear.
==511403==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==511403== Warning: unimplemented fcntl command: 1033
==511403== Invalid write of size 4
==511403==    at 0x2F3123: unicode::script_segmenter::mergeSets(unicode::fs_array<unicode::Script, 32ul> const&, unicode::fs_array<unicode::Script, 32ul>&) (script_segmenter.cpp:97)
==511403==    by 0x2F2C31: unicode::script_segmenter::consume() (script_segmenter.cpp:31)
==511403==    by 0x2B8733: unicode::script_segmenter::consume(unicode::out<unsigned long>, unicode::out<unicode::Script>) (script_segmenter.h:57)
==511403==    by 0x2BDC1E: void unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consumeUntilSplitPosition<unicode::script_segmenter, unicode::Script>(unicode::script_segmenter&, unicode::out<unsigned long>, unicode::out<unicode::Script>) (run_segmenter.h:164)
==511403==    by 0x2BC14B: void unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consumeAllUntilSplitPosition<0ul, unicode::script_segmenter, unicode::emoji_segmenter>() (run_segmenter.h:143)
==511403==    by 0x2B9AE4: unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consume(unicode::out<unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::range>) (run_segmenter.h:112)
==511403==    by 0x2B6364: terminal::renderer::TextRenderer::requestGlyphPositions() (TextRenderer.cpp:192)
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==  Address 0x1fff001000 is not stack'd, malloc'd or (recently) free'd
==511403== 
==511403== 
==511403== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==511403==  Access not within mapped region at address 0x1FFF001000
==511403==    at 0x2F3123: unicode::script_segmenter::mergeSets(unicode::fs_array<unicode::Script, 32ul> const&, unicode::fs_array<unicode::Script, 32ul>&) (script_segmenter.cpp:97)
==511403==    by 0x2F2C31: unicode::script_segmenter::consume() (script_segmenter.cpp:31)
==511403==    by 0x2B8733: unicode::script_segmenter::consume(unicode::out<unsigned long>, unicode::out<unicode::Script>) (script_segmenter.h:57)
==511403==    by 0x2BDC1E: void unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consumeUntilSplitPosition<unicode::script_segmenter, unicode::Script>(unicode::script_segmenter&, unicode::out<unsigned long>, unicode::out<unicode::Script>) (run_segmenter.h:164)
==511403==    by 0x2BC14B: void unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consumeAllUntilSplitPosition<0ul, unicode::script_segmenter, unicode::emoji_segmenter>() (run_segmenter.h:143)
==511403==    by 0x2B9AE4: unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::consume(unicode::out<unicode::basic_run_segmenter<unicode::script_segmenter, unicode::emoji_segmenter>::range>) (run_segmenter.h:112)
==511403==    by 0x2B6364: terminal::renderer::TextRenderer::requestGlyphPositions() (TextRenderer.cpp:192)
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==    by 0x3700000036: ???
==511403==  If you believe this happened as a result of a stack
==511403==  overflow in your program's main thread (unlikely but
==511403==  possible), you can try to increase the size of the
==511403==  main thread stack using the --main-stacksize= flag.
==511403==  The main thread stack size used in this run was 8388608.
==511403== 
==511403== HEAP SUMMARY:
==511403==     in use at exit: 61,971,679 bytes in 41,185 blocks
==511403==   total heap usage: 278,637 allocs, 237,452 frees, 5,313,727,825 bytes allocated
==511403== 
==511403== LEAK SUMMARY:
==511403==    definitely lost: 26,148 bytes in 71 blocks
==511403==    indirectly lost: 31,283 bytes in 324 blocks
==511403==      possibly lost: 46,388,796 bytes in 109 blocks
==511403==    still reachable: 15,472,036 bytes in 40,241 blocks
==511403==                       of which reachable via heuristic:
==511403==                         length64           : 2,328 bytes in 42 blocks
==511403==                         newarray           : 1,936 bytes in 41 blocks
==511403==                         multipleinheritance: 104 bytes in 1 blocks
==511403==         suppressed: 0 bytes in 0 blocks
==511403== Rerun with --leak-check=full to see details of leaked memory
==511403== 
==511403== For lists of detected and suppressed errors, rerun with: -s
==511403== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault
[schwarzgerat](139) $ 
```

## Environment

See information above, especially regarding `TERM`.

## Steps to Reproduce

See above. I'm happy to run valgrind/gdb/whatever to help you out, subject to time demands from elsewhere, but we're all in on this terminal ecosystem together =].

### PR DESCRIPTION
**Pull request by christianparpart**
Refs #217 

Checklist of broken tests:

* [x] XTSMGRAPHICS for sixel graphics geometry (Pi: 2)
* [x] fix zalgo screen resize crash
* [x] zalgo: fix line 4
* [x] zalgo: fix bottom line
* [x] demo test: `u` (unicode) -> causes excess to glyph cache
* [x] fix rendering when texture atlas gets full (should create new atlas).
* [x] demo test: `j` (jungle) -> maybe VT some sequence not conforming?
* [ ] ~zalgo: fix line 7 and 8 (not good or missing decorations)~
* [ ] ~reproduce and fix #217's `Calculated current line does not match.`~

This PR also implements #221 (that fixed the jungle notcurses-demo)

The remaining two items will be addressed separately.

### CODE REVIEW

**Comment by dankamongmen** [comment]
loving this! =]

**Comment by christianparpart** [comment]
> loving this! =]

Thanks. There is more to come. But the pr should not have grown too big.

I need to fix excessive glyph cache use. I wonder what other TEs are doing when facing an app that walks through the full unicode table.

**Comment by dankamongmen** [comment]
heh, i had one test in there, `allglyph`, which i replaced with `animate` because so many terminals fell over on it. it looped through the 17 unicode planes, emitting every printable glyph once, as fast as it could. alacritty was pretty fast (<5s), but i think alacritty punts on a lot of glyphs (i've never seen emoji work well there). VTE had tremendous pains, usually requiring about 45s. kitty was somewhere in the middle.

if there's any particular area you want to test/benchmark, feel free to hit me up -- i've got a lot of little programs exercising various things.

**Comment by christianparpart** [comment]
What tag/branch should I check out to get access to `allglyph`? - worst case i just grep through the `git log -p` :)

I remember I once checked kitty as well as alacritty (and a little wezterm) to see what they're doing to render.
kitty and alacritty both are just checking for grapheme boundaries and render the codepoints into seperate glyphs. That is certainly speedy but you do not handle more complex emoji or ligatures. You can then manually implement that in your code paths, but then I wonder why not using harfbuzz right away (that's why harfbuzz does exist, IMHO). So I am using harfbuzz, which is expensive as it respects all of these corner cases, at least I am therefore able to properly render all types of complex emoji sequences - but my caching layer seems to explode (on excess).

Alacritty is particulary fast because the render loop thread looks like this:

```
render loop {
    acquire terminal lock
    copy out screen buffer
    release terminal lock
    prepare GL render buffers
    upload render buffers and execute (with very clever use of GL, kudows here)
    swap GL buffers (and wait for vsync)
}
```
I think what makes alacritty so really fast is the fact of having that copy-out action (to keep the mutex lock time at a minimum) + a the tons of GL optimizations + vsync.
So when `allglyph` test is ran, most of the codepoints don't even land into the glyph cache or the texture atlas map.
My GL code isn't that sophisticated (hopefully it one day will be :-D), but the copy-out is one thing I want to investigate soon, too.

**Comment by dankamongmen** [comment]
i know for a fact that kitty implements some cojoined emoji; here's fitzpatrick toning

2021-05-26-024434_1072x638_scrot

the `mojibake` demo ought run through all defined emoji; if there are any i'm missing that ought show off `contour` well, let me know!

if you really want to run `allglyph`, it was replaced in 2.1.5, so 2.1.4 has it: https://github.com/dankamongmen/notcurses/releases/tag/v2.1.4

**Pull request merged**
